services:
  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
    image: 'citusdata/citus:12.1.3' 
    ports:
      - "${MASTER_EXTERNAL_PORT:-5532}:5432"
    labels: [ "com.citusdata.role=master" ]
    env_file: .env
    volumes:
      - citus_master_data:/var/lib/postgresql/data
    networks: [ backend ]      

  worker:
    image: "citusdata/citus:12.1.3"
    labels: ["com.citusdata.role=Worker"]
    depends_on: [manager]
    env_file: .env
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck-volume:/healthcheck      
    networks: [ backend ]

  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck-volume:/healthcheck
    depends_on: [master]
    env_file: .env
    networks: [ backend ]

  tarantool:
    image: tarantool/tarantool:latest
    container_name: tarantool_db
    ports:
      - "3301:3301"
    env_file: .env
    command: tarantool /opt/tarantool/init.lua
    volumes:      
      - ./init/init-in-memory-db.lua:/opt/tarantool/init.lua
      - tarantool_data:/var/lib/tarantool
    networks: [ backend ]

  haproxy:
    image: haproxy:latest
    container_name: messenger-haproxy
    ports:
      - "5432:5432"
      - "8404:8404"
    volumes:
      - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - master
      - worker
    networks:
      - [ backend ]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "haproxy", "-c", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
      interval: 10s
      timeout: 5s
      retries: 3

  messenger:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - haproxy
      - tarantool
    networks:
      - [ backend, frontend ]
    restart: unless-stopped

  nginx:
    image: nginx:1.25-1.25-alpine
    ports: 
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - messenger
    networks: [ frontend ]
    restart: unless-stopped

networks:
  backend:
    name: "messenger_backend"
    driver: bridge
  frontend:
    name: "messenger_frontend"
    driver: bridge

volumes:
  healthcheck-volume:
  citus_master_data:  
  tarantool_data:  