services:

  postgres:
    container_name: postgres-messenger
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=messenger
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5528:5432"
    networks:
      - backend
    restart: unless-stopped

  tarantool:
    image: tarantool/tarantool:latest
    container_name: tarantool_db
    ports:
      - "3301:3301"
    env_file: .env
    command: tarantool /opt/tarantool/init.lua
    volumes:
      - ./init/init-in-memory-db.lua:/opt/tarantool/init.lua
      - tarantool_data:/var/lib/tarantool
    networks: [ backend ]
    restart: unless-stopped

  messenger_1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: messenger_1
    ports:
      - "3001:3000"
    env_file:
      - .env   
      - .env.secret
    depends_on:
      - postgres
      - tarantool    
    networks: [ backend, frontend ]
    restart: unless-stopped

  messenger_2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: messenger_2
    ports:
      - "3002:3000"
    env_file:
      - .env
      - .env.secret
    depends_on:
      - postgres
      - tarantool    
    networks: [ backend, frontend ]
    restart: unless-stopped

  messenger_3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: messenger_3
    ports:
      - "3003:3000"
    env_file:
      - .env
      - .env.secret
    depends_on:
      - postgres
      - tarantool    
    networks: [ backend, frontend ]
    restart: unless-stopped

  nginx:
    image: nginx:1.25-alpine
    container_name: messenger-nginx
    ports: 
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - messenger_1
      - messenger_2
      - messenger_3
    networks: [ frontend ]
    restart: unless-stopped

  node_exporter:
    container_name: messenger-node-exporter
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    networks: [ backend ]
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'


  prometheus:
    container_name: messenger-prometheus
    image: prom/prometheus:latest
    ports:
      - "9092:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks: [ backend, frontend ]
    extra_hosts:
      - "host.docker.internal:host-gateway"  # <--- Добавьте эту строку, чтобы Prometheus знал этот адрес
    depends_on:
      - messenger_1
      - messenger_2
      - messenger_3
    restart: unless-stopped

  alertmanager:
    container_name: messenger-alertmanager
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    command: 
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    depends_on:
      - prometheus
    restart: unless-stopped

  grafana:
    container_name: messenger-grafana
    image: grafana/grafana:latest
    ports:
      - "4001:3000"    
    environment:
      - GF_SECURITY=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_HTTP_PORT=3000
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro      
      - grafana_data:/var/lib/grafana
    networks: [ backend ]
    depends_on:
      - prometheus
    restart: unless-stopped  


networks:
  backend:
    name: "messenger_backend"
    driver: bridge
  frontend:
    name: "messenger_frontend"
    driver: bridge

volumes:
  healthcheck-volume: 
  tarantool_data:  
  prometheus_data:
  grafana_data:
  pg_data: