services:
  grafana:
    container_name: messenger-grafana
    image: grafana/grafana:13.0
    ports:
      - "4001:4001"    
    environment:
      - GF_SECURITY=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    networks: 
      - monitoring
    restart: unless-stopped
    
networks:
  monitoring:
    name: monitoring_network
    driver: bridge 

volumes:
  grafana_data: