POST http://localhost:3001/dialog/b9b0f7cf-aa97-47b9-a046-6450874cd8b8/send
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiODFlMTc1ZDYtYjE1ZC00ZDYzLWFkMDctZGY0YzM5YjNiYmU4IiwiZXhwIjoxNzkwMDk0NDk4LCJ0b2tlbiI6bnVsbCwicmVxdWVzdF9pZCI6bnVsbH0.Da2oYqr4XJA1NMv_9ZJ-KrRUw6Ris9GY18aAYnKkaM0
content-type: application/json
accept: application/json

{    
    "text": "Hope just fine! 1"
}
