services:

  redis:
    image: redis:7-alpine
    container_name: redis_app_cs
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - ./redis_data:/data
    command: redis-server --requirepass secure_password --appendonly yes

  postgres-cs:
    image: postgres:13.3
    container_name: postgres_cs
    environment:
      POSTGRES_DB: "highload"
      POSTGRES_USER: "pguser"
      POSTGRES_PASSWORD: "pgpassword"      
    ports:
      - "5432:5432"
    volumes:    
      - cs-postgres-data:/var/lib/postgresql/data

volumes:
  cs-postgres-data:      