PUT http://localhost:3000/friend/set/ee604651-14e5-4ea4-90d8-27e55870fb04
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiZWU2MDQ2NTEtMTRlNS00ZWE0LTkwZDgtMjdlNTU4NzBmYjA0IiwiZXhwIjoxNzY4MjEyMDA4fQ.a7sP9qRWLpoZXfoppf3hapQYxuvOgQaOqsMMx7McaF0
content-type: application/json
accept: application/json

