http://localhost:3000/user/get/3bb34cee-a28b-4b33-a35e-5e2d008fb2f4
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIzYmIzNGNlZS1hMjhiLTRiMzMtYTM1ZS01ZTJkMDA4ZmIyZjQiLCJleHAiOjE3NjMzOTM1NTJ9.uZNYH1gkg_65fYCXhZC_G7VY9j-EpJclPq0TQZC4rAg