/*
 * OTUS Highload Architect
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DialogUserIdSendPostRequest {
    /// Текст сообщения
    #[serde(rename = "text")]
    pub text: String,
}

impl DialogUserIdSendPostRequest {
    pub fn new(text: String) -> DialogUserIdSendPostRequest {
        DialogUserIdSendPostRequest {
            text,
        }
    }
}

