/*
 * OTUS Highload Architect
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DialogUserIdSendPost500Response {
    /// Описание ошибки
    #[serde(rename = "message")]
    pub message: String,
    /// Идентификатор запроса. Предназначен для более быстрого поиска проблем.
    #[serde(rename = "request_id", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
    /// Код ошибки. Предназначен для классификации проблем и более быстрого решения проблем.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<i32>,
}

impl DialogUserIdSendPost500Response {
    pub fn new(message: String) -> DialogUserIdSendPost500Response {
        DialogUserIdSendPost500Response {
            message,
            request_id: None,
            code: None,
        }
    }
}

