/*
 * OTUS Highload Architect
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DialogMessage {
    /// Идентификатор пользователя
    #[serde(rename = "from")]
    pub from: String,
    /// Идентификатор пользователя
    #[serde(rename = "to")]
    pub to: String,
    /// Текст сообщения
    #[serde(rename = "text")]
    pub text: String,
}

impl DialogMessage {
    pub fn new(from: String, to: String, text: String) -> DialogMessage {
        DialogMessage {
            from,
            to,
            text,
        }
    }
}

