POST http://localhost:3000/post
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiZjQ5YTY3YTUtM2Y4Ny00ODk1LThkYzMtM2ZmMzAwOWQ5YTliIiwiZXhwIjoxNzcyNjEyMzI2fQ.XXqonjE_aeQPzynyHJzJALgMs0nil1qw6i4hdP9IiCY
content-type: application/json
accept: application/json

{    
    "text": "Hey all! I'm friend number one! 5"
}
