POST http://localhost:3000/post
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMjk4MjBlZWMtNTQ5NS00OWQ3LTlhMmYtMGE5ZDk3NDM4OTc2IiwiZXhwIjoxNzc0Mjc3MDUxfQ.U3YwVGZ-fZncQHUpBFXxa4OVppQoA676qgNc9EygwiU
content-type: application/json
accept: application/json

{    
    "text": "Hey all! I'm friend number one! 5"
}
