POST http://localhost:3000/user/register
content-type: application/json
accept: application/json

{
    "first_name": "Евгений",    
    "last_name": "Нявро",
    "password": "secret",
    "birthdate": "1990-01-01",
    "biography": "bio bio",
    "city": "Новосибирск"
}
